### ISSUE TITLE
Tmux configuration breaks

### ISSUE THREAD

**Issue by tjbcg** [PH111P/powerline#2]
After migrating from `powerline/powerline` to `PH111P/powerline`, my tmux config breaks (I get the tmux' default green bar).

When using `powerline-lint`, the script fails, but still shows `'found duplicate key'`:
```python
Traceback (most recent call last):
  File "/home/fliife/bin/powerline-lint", line 13, in <module>
    sys.exit(check(args.config_path, args.debug))
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/__init__.py", line 450, in check
    find_all_ext_config_files(search_paths, 'themes'),
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/__init__.py", line 379, in find_all_ext_config_files
    'type': subdir,
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/__init__.py", line 335, in updated_with_config
    hadproblem, config, error = load_json_file(d['path'])
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/__init__.py", line 327, in load_json_file
    config, hadproblem = load(F)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/__init__.py", line 16, in load
    r = loader.get_single_data()
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/constructor.py", line 48, in get_single_data
    return self.construct_document(node)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/constructor.py", line 57, in construct_document
    for dummy in generator:
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/constructor.py", line 252, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/constructor.py", line 205, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/constructor.py", line 19, in f
    return gen_marked_value(func(self, node, *args, **kwargs), node.start_mark)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/constructor.py", line 140, in construct_mapping
    'found duplicate key', key_node.start_mark
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/lint/markedjson/loader.py", line 24, in echoerr
    echoerr(*args, **kwargs)
TypeError: echoerr() takes exactly 0 arguments (4 given)
```

I installed powerline through `yaourt -S powerline-i3-git`

[Here](https://hastebin.com/iximoxucur.json) is my theme, and [here](https://hastebin.com/eyicazekav.json) is my colourscheme. [These](https://hastebin.com/zahuputuca.json) are my defined colours.

Please note that this config works fine with the classic powerline

Also, **important note**, the **`default`** theme and colourscheme doesn't work either.
Somehow, I was able to get something like `hl() has unknown argument click` (something like that), but I fail to reproduce this error message. I'll let you know if I manage to find the exact message

**EDIT**: The exact error I described above is the following:
```python
Traceback (most recent call last):
  File "/home/fliife/bin/powerline-config", line 22, in <module>
    args.function(pl, args)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/commands/config.py", line 15, in
__call__
    self.function(*args, **kwargs)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 211, in tmux_setup
    init_tmux_environment(pl, args, set_tmux_environment=ste)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/bindings/config.py", line 125, in init_tmux_environment
    set_tmux_environment(varname, powerline.renderer.hlstyle(**highlight)[2:-1])
TypeError: hlstyle() got an unexpected keyword argument 'click'
```
It can be obtained by running `powerline-config tmux setup`

**Comment by PH111P** [comment]
This was actually no problem with your config files, but a bug.

However, I will look into the problem with powerline-lint.

**Comment by tjbcg** [comment]
Also, is there any documentation (relative to the changes this fork brings ?)
It looks really interesting, but I have no idea how to configure click-ability for segments.

**Comment by PH111P** [comment]
There will be. 

You can configure the click-ability for segments via the color scheme by adding a click field, e.g.:

    "workspace": { "fg": "0xe4e4e4", "bg": "0x0087af", "click": { "left": "i3-msg workspace {0:.2}", "right": "i3-msg move to workspace {0:.2}" } },

In the `click` dictionary you can map `left`, `right`, `middle`, `scroll up` and `scroll down` to a string that will be executed (if the bar was started with the `--clicks` argument, otherwise nothing will happen) when the corresponding button was pressed. You may also use a placeholder to get the segment's content, as seen in the example above.

**Comment by tjbcg** [comment]
Hi.
Until now, I hadn't had the time to try this (I switched over to upstream powerline).
I just reinstalled that through yaourt, and the same `hl() got an unexpected argument 'click'` error pops up, replacing tmux' statusline and my prompt.

If I kill the powerline daemon, this error pops up:
```python
2016-12-29 20:40:42,284:ERROR:shell:powerline:Failed to render: hl() got an unexpected keyword argument 'click'
Traceback (most recent call last):
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/__init__.py", line 870, in render
    return self.renderer.render(*args, **kwargs)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/renderers/shell/__init__.py", line 95, in render
    **kwargs
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/renderer.py", line 299, in render
    theme=theme,
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/renderers/shell/__init__.py", line 106, in do_render
    return super(ShellRenderer, self).do_render(segment_info=segment_info, **kwargs)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/renderers/shell/__init__.py", line 68, in do_render
    **kwargs
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/renderer.py", line 397, in do_render
    for segment in self._render_segments(theme, segments)
  File "/home/fliife/local/lib/python2.7/site-packages/powerline/renderer.py", line 549, in _render_segments
    contents_highlighted = self.hl(self.escape(contents_raw), **segment['highlight'])
TypeError: hl() got an unexpected keyword argument 'click'
```

I checked, and files are up-to-date with the repository. `powerline-lint` is fixed, but brings up nothing relevant

**Comment by tjbcg** [comment]
I managed to fix this this way:

- List all the files containing `fg=None, bg=None, attrs=None` (that is, `hl` or `hlstyle` definitions)
    ```
    ack "fg=None, bg=None, attrs=None"
    ```
- For each element, if the argument list stops at `attrs=None`, add the `click=None` argument. It means that 
    ```python
    def hlstyle(self, fg=None, bg=None, attrs=None)
    ```
    Becomes
    ```python
    def hlstyle(self, fg=None, bg=None, attrs=None, click=None)
    ```

I think what fixed it was applying this very change to `powerline/renderer.py`

**Comment by PH111P** [comment]
I thought I had fixed this everywhere, but apparently I was wrong. Thanks, it should work now.
